server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #下面的配置是对8001微服务套个网关
  cloud:
    gateway:
      discovery:        #(!!!配置动态路由加上这一行)
        locator:        #(!!!配置动态路由加上这一行)
          enable: true  #(!!!配置动态路由加上这一行)开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh     #payment_route   #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #（!!!配置动态路由时，用这个取代上面的一行）匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2    #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #（!!!配置动态路由时，用这个取代上面的一行）匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**    #断言，路径相匹配的进行路由
#            - Method=GET
#            - After=2021-03-19T15:46:44.179+08:00[Asia/Shanghai]
#            - Header=X-Request-Id,\d+   #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Cookie=username,zzyy
#          filters:   #gatewayfilter
#            - AddRequestParameter=red,blue



#不配动态路由 只需要启动9527 8001 7001
#配置动态路由 要启动9527 8001 8002 7001  访问http://localhost:9527/payment/lb 测试

eureka:
  instance:
    hostname: cloud-gateway-service
  client:   #服务提供方provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
